import { SkinTheme, SkinThemeId } from '../types';
export type { SkinTheme, SkinThemeId };

export const SKIN_THEMES: SkinTheme[] = [
  {
    id: 'cyber_neon',
    nameDe: 'Cyberpunk Neon',
    nameEn: 'Cyberpunk Neon',
    icon: '⚡',
    badge: 'CYBER-CORE',
    descriptionDe: 'Elektrisches Cyan, leuchtendes Violett & futuristische Sci-Fi-Optik.',
    descriptionEn: 'Electric cyan, glowing violet & futuristic sci-fi neon styling.',
    bodyBgClass: 'from-slate-950 via-indigo-950 to-purple-950',
    appWrapperClass: 'theme-cyber-neon',
    cardBgClass: 'bg-slate-900/80 border-cyan-500/30 shadow-cyan-500/10',
    borderClass: 'border-cyan-500/40',
    accentGradient: 'from-cyan-400 via-blue-500 to-fuchsia-500',
    textAccent: 'text-cyan-400',
    glowColor: '#06b6d4',
    previewColors: ['#06b6d4', '#3b82f6', '#d946ef', '#0f172a'],
  },
  {
    id: 'cosmic_galaxy',
    nameDe: 'Kosmische Galaxie',
    nameEn: 'Cosmic Galaxy',
    icon: '🌌',
    badge: 'NEBULA-STAR',
    descriptionDe: 'Tiefschwarzer Weltraum, Sternenstaub-Indigo und strahlendes Gold.',
    descriptionEn: 'Deep space void, stardust indigo, and brilliant starlight gold.',
    bodyBgClass: 'from-[#08071a] via-[#120e36] to-[#201147]',
    appWrapperClass: 'theme-cosmic-galaxy',
    cardBgClass: 'bg-[#15123d]/80 border-purple-500/30 shadow-purple-500/10',
    borderClass: 'border-purple-500/40',
    accentGradient: 'from-amber-300 via-purple-500 to-indigo-600',
    textAccent: 'text-purple-300',
    glowColor: '#a855f7',
    previewColors: ['#fbbf24', '#a855f7', '#4f46e5', '#08071a'],
  },
  {
    id: 'emerald_forest',
    nameDe: 'Smaragd-Dschungel',
    nameEn: 'Emerald Forest',
    icon: '🌿',
    badge: 'BIO-NATURE',
    descriptionDe: 'Saftiges Waldgrün, leuchtende Minze und lebendige Natur-Vibes.',
    descriptionEn: 'Lush jungle greens, vibrant bioluminescent mint, and nature energy.',
    bodyBgClass: 'from-[#051a14] via-[#08291e] to-[#041f17]',
    appWrapperClass: 'theme-emerald-forest',
    cardBgClass: 'bg-[#082e22]/80 border-emerald-500/30 shadow-emerald-500/10',
    borderClass: 'border-emerald-500/40',
    accentGradient: 'from-emerald-400 via-teal-400 to-green-500',
    textAccent: 'text-emerald-400',
    glowColor: '#10b981',
    previewColors: ['#34d399', '#10b981', '#059669', '#051a14'],
  },
  {
    id: 'sunset_arcade',
    nameDe: 'Sunset Arcade',
    nameEn: 'Sunset Arcade',
    icon: '🌅',
    badge: 'RETRO-WAVE',
    descriptionDe: 'Warme Abendrot-Orangetöne, Koralle und Neon-Pink im 80er Retro-Stil.',
    descriptionEn: 'Warm sunset orange, bright coral, and neon pink 80s arcade vibes.',
    bodyBgClass: 'from-[#1c0b1e] via-[#2c102b] to-[#3a1523]',
    appWrapperClass: 'theme-sunset-arcade',
    cardBgClass: 'bg-[#2b1028]/80 border-orange-500/30 shadow-orange-500/10',
    borderClass: 'border-orange-500/40',
    accentGradient: 'from-amber-400 via-orange-500 to-rose-500',
    textAccent: 'text-orange-400',
    glowColor: '#f97316',
    previewColors: ['#fbbf24', '#f97316', '#f43f5e', '#1c0b1e'],
  },
  {
    id: 'candy_pastel',
    nameDe: 'Candy Pop Traum',
    nameEn: 'Candy Pop Dream',
    icon: '🍬',
    badge: 'SWEET-PASTEL',
    descriptionDe: 'Sanfte Pastellfarben: Zuckerwatte-Rosa, sanftes Lavendel & Himmelblau.',
    descriptionEn: 'Gentle pastel sweetness: cotton candy pink, soft lavender & sky blue.',
    bodyBgClass: 'from-[#1a152e] via-[#26173d] to-[#1f1e3d]',
    appWrapperClass: 'theme-candy-pastel',
    cardBgClass: 'bg-[#291e47]/80 border-pink-400/30 shadow-pink-400/10',
    borderClass: 'border-pink-400/40',
    accentGradient: 'from-pink-300 via-purple-300 to-sky-300',
    textAccent: 'text-pink-300',
    glowColor: '#f472b6',
    previewColors: ['#f472b6', '#c084fc', '#38bdf8', '#1a152e'],
  },
  {
    id: 'steampunk_gold',
    nameDe: 'Steampunk Bronze & Gold',
    nameEn: 'Steampunk Brass & Gold',
    icon: '⚙️',
    badge: 'BRASS-GEAR',
    descriptionDe: 'Edles Messing, polierte Zahnräder, Bernstein & edle Kupfer-Eleganz.',
    descriptionEn: 'Vintage brass, polished gears, warm amber & mechanical copper elegance.',
    bodyBgClass: 'from-[#1c140a] via-[#2a1c0d] to-[#1f150b]',
    appWrapperClass: 'theme-steampunk-gold',
    cardBgClass: 'bg-[#2c1d10]/80 border-amber-500/30 shadow-amber-500/10',
    borderClass: 'border-amber-500/40',
    accentGradient: 'from-yellow-300 via-amber-500 to-orange-600',
    textAccent: 'text-amber-300',
    glowColor: '#eab308',
    previewColors: ['#fde047', '#f59e0b', '#b45309', '#1c140a'],
  },
  {
    id: 'deep_ocean',
    nameDe: 'Tiefsee Ozean',
    nameEn: 'Deep Ocean Trench',
    icon: '🌊',
    badge: 'AQUA-DEPTH',
    descriptionDe: 'Geheimnisvolles Tiefsee-Blau, Aquamarin & leuchtende Korallen-Akzente.',
    descriptionEn: 'Mysterious deep sea blue, glowing aquamarine & vibrant reef coral.',
    bodyBgClass: 'from-[#031526] via-[#05213b] to-[#041a2e]',
    appWrapperClass: 'theme-deep-ocean',
    cardBgClass: 'bg-[#062947]/80 border-sky-500/30 shadow-sky-500/10',
    borderClass: 'border-sky-500/40',
    accentGradient: 'from-sky-400 via-teal-300 to-cyan-500',
    textAccent: 'text-sky-300',
    glowColor: '#0ea5e9',
    previewColors: ['#38bdf8', '#2dd4bf', '#0284c7', '#031526'],
  },
];

export const getSkinTheme = (skinId?: string): SkinTheme => {
  const found = SKIN_THEMES.find((s) => s.id === skinId);
  return found || SKIN_THEMES[0];
};
